### ISSUE TITLE
error 9014

### ISSUE THREAD

**Issue by vietgameplay** [iamport/iamport-ios#11]
Hello,
I got the error some days ago on both Android and IOS. Could you please help me to solve it
`error_msg: Optional("다날 서버로부터 받은 응답이 올바르지 않습니다.[인증실패] 업체정보에 이상이 있습니다. 해당 서비스 업체로 문의하여 주십시오.")
      - some: "다날 서버로부터 받은 응답이 올바르지 않습니다.[인증실패] 업체정보에 이상이 있습니다. 해당 서비스 업체로 문의하여 주십시오."
    ▿ error_code: Optional("9014")
      - some: "9014"`

**Comment by kjh5833** [comment]
Hi. Thank you for using our sdk.
It's not an sdk issue.
[9014] is usually caused by non-payment to danal.
Please check with danal.
