### ISSUE TITLE
CocoaPods RxSwift 6.0 지원 문의

### ISSUE THREAD

**Issue by kanz-kang** [iamport/iamport-ios#32]
안녕하세요.

README의 Installation을 보면 RxSwift 6.x 는 SPM으로만 지원하고 계신것 같은데
혹시 CocoaPod 으로도 6.x 지원 계획이 있으신지 문의 드립니다.

감사합니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
먼저 `1.3.0-hotfix01` 에서 CocoaPods 방식으로 사용하실 수 있으니 참고바랍니다.
https://github.com/iamport/iamport-ios/pull/34
