### ISSUE TITLE
결제품목명에 ' 문자열이 존재하는 경우 결제가 불가능한 오류

### ISSUE THREAD

**Issue by seunghyunjin** [iamport/iamport-ios#37]
안녕하세요. 문의사항이 있어 Issue 에 남깁니다. 

> 현재 iamport-ios 1.3.2 버전 사용중입니다.

```
var request = IamPortRequest( pg: pgId, merchant_uid: muid, amount: paymentPrice)
request.name = "테스트상품'"
...
// 웹뷰를 이용해 결제 요청 
Iamport.shared.paymentWebView(webViewMode: webView, userCode: ###, iamPortRequest: request)
```

위와 같이 요청되는 경우,  웹뷰 자체는 리다이렉션이 이뤄지긴 하는데 
정상 조건(' 를 포함하지 않는 상품명 ) 인 경우와 비교하여 
모바일 결제화면 직전에서 리다이렉션이 되지 않습니다.
웹뷰에는 빈 화면만 노출되고 있는 상태로 변화가 없습니다. 

Request 에 상품명을 설정할 때 상품명 문자열에 대해 별도 처리가 필요할까요? 

감사합니다.

**Comment by kanz-kang** [comment]
@seunghyunjin 안녕하세요. 

저는 support@iamport.kr 에 직접 문의를 드렸었는데요.
아래와 같이 답변을 주셨었습니다. 

```
single quote 값이 유입되지 않도록 앞단에서 replace 함수를 통해 다른 값으로 변환해주시는 작업이 필요합니다.
```

혹시 모르니, 기술지원 문의 메일로 체크해보시는 게 좋을 것 같습니다.

**Comment by seunghyunjin** [comment]
@kanz-kang 
일단 저도 동일하게 처리하고, 차주에 문의 메일 발송 해보도록 하겠습니다.
답변 정말 감사합니다.  🙏
