### ISSUE TITLE
카카오와 함께 설치시 설치에러가 발생합니다.

### ISSUE THREAD

**Issue by sechan-hwang** [iamport/iamport-ios#8]
https://github.com/iamport/iamport-ios/issues/7#issue-864591151

해결방법이 있나요?

**Comment by kjh5833** [comment]
관리 포인트를 하나로 만들기 위해 해당 이슈는 닫겠습니다.
https://github.com/iamport/iamport-ios/issues/9
위 링크에서 최신 내역을 확인 부탁드립니다.
