### ISSUE TITLE
Pods 설치시 에러

### ISSUE THREAD

**Issue by ethan1598** [iamport/iamport-ios#9]
![스크린샷 2021-04-22 오후 3 13 16](https://user-images.githubusercontent.com/83000937/115679467-94607e00-a38d-11eb-9545-198366b2c427.png)

Alamofire와 Kakao의 충돌로 인해 설치가 안 되던데 혹시 해결 방법이 있을까요?

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
kakaosdk 의 Alamofire 메이저 버전이 5로 업데이트 되면서,
기존의 저희 라이브러리와 호환이 안되어 충돌하는 것 같습니다.
관련 사항 수정하여 `0.0.3-dev11` 를 배포하였으니
`pod 'iamport-ios', '0.0.3-dev11' ` 해당 sdk 로 확인 부탁드립니다.
감사합니다.

**Comment by ethan1598** [comment]
정상적으로 설치되었습니다. 확인 감사합니다.

**Comment by kjh5833** [comment]
확인 감사드리며, 또한 저희 서비스에 관심 가져주셔서 감사합니다.
해당 이슈는 닫도록 하겠습니다.
